### ISSUE TITLE
Ignoring rules

### ISSUE THREAD

**Issue by nodesocket** [HippoPHP/Hippo#46]
How can I specify I don't care about:

    (info) : Prefer single quotes to double

and

    (error) : Line is too long.

And ignore them.

**Comment by jbrooksuk** [comment]
So if you create a custom config file, say we call it `nodesocket.yml` you can do this:

```yml
name: "nodesocket"
extends: "PSR-2"

file:
  max_line_length:
    enabled: false
style:
  quotes:
    style: "double"
```

Then you can run Hippo with your config file:

```bash
$ ./bin/hippo ./src -c=nodesocket.yml
```
